name: ProtocolLib full build lifecycle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      targetBranch:
        description: 'Target branch to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Run gradle build lifecycle
        run: ./gradlew build shadowJar --no-daemon

      - name: Upload plugin file
        uses: actions/upload-artifact@v4
        with:
          name: ProtocolLib
          path: build/libs/ProtocolLib.jar
